// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jabil_test.Models;

namespace jabil_test.Migrations
{
    [DbContext(typeof(MaterialsContext))]
    partial class MaterialsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("jabil_test.Models.Building", b =>
                {
                    b.Property<int>("PKBuilding")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PKBuilding")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Building")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("PKBuilding");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            PKBuilding = 1,
                            Available = true,
                            Name = "Building1"
                        },
                        new
                        {
                            PKBuilding = 2,
                            Available = true,
                            Name = "Building2"
                        },
                        new
                        {
                            PKBuilding = 3,
                            Available = false,
                            Name = "Building3"
                        });
                });

            modelBuilder.Entity("jabil_test.Models.Customer", b =>
                {
                    b.Property<int>("PKCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PKCustomer")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available");

                    b.Property<int>("FKBuilding")
                        .HasColumnName("FKBuilding");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Customer")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.HasKey("PKCustomer");

                    b.HasIndex("FKBuilding");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            PKCustomer = 1,
                            Available = true,
                            FKBuilding = 1,
                            Name = "Luis",
                            Prefix = "cust1"
                        },
                        new
                        {
                            PKCustomer = 2,
                            Available = true,
                            FKBuilding = 2,
                            Name = "Pedro",
                            Prefix = "cust2"
                        },
                        new
                        {
                            PKCustomer = 3,
                            Available = false,
                            FKBuilding = 2,
                            Name = "Juan",
                            Prefix = "cust3"
                        });
                });

            modelBuilder.Entity("jabil_test.Models.PartNumber", b =>
                {
                    b.Property<int>("PKPartNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PKPartNumber")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available");

                    b.Property<int>("FKCustomer")
                        .HasColumnName("FKCustomer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("PartNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("PKPartNumber");

                    b.HasIndex("FKCustomer");

                    b.ToTable("PartNumbers");

                    b.HasData(
                        new
                        {
                            PKPartNumber = 1,
                            Available = true,
                            FKCustomer = 1,
                            Name = "P1231"
                        },
                        new
                        {
                            PKPartNumber = 2,
                            Available = true,
                            FKCustomer = 2,
                            Name = "P5322"
                        },
                        new
                        {
                            PKPartNumber = 3,
                            Available = false,
                            FKCustomer = 2,
                            Name = "P5232"
                        });
                });

            modelBuilder.Entity("jabil_test.Models.Customer", b =>
                {
                    b.HasOne("jabil_test.Models.Building", "Building")
                        .WithMany("Customers")
                        .HasForeignKey("FKBuilding")
                        .HasConstraintName("FK_Customers_Buildings")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("jabil_test.Models.PartNumber", b =>
                {
                    b.HasOne("jabil_test.Models.Customer", "Customer")
                        .WithMany("PartNumbers")
                        .HasForeignKey("FKCustomer")
                        .HasConstraintName("FK_PartNumbers_Customers")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
